In [1]:
# ==========================================
# LIBRERÍAS
# ==========================================

import pandas as pd
import numpy as np

# ==========================================
# CARGA DE DATOS
# ==========================================

df = pd.read_csv(
    "../../Datos/saber11_limpio_base.csv"
)

print(df.shape)

df.head()

(301723, 52)

,periodo,estu_consecutivo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_codigo_icfes,cole_depto_ubicacion,...,punt_global,anio,fami_personashogar_num,fami_cuartoshogar_num,fami_estratovivienda_num,estu_fechanacimiento_dt,edad,densidad_hogar,indice_tecnologico,indice_bienes_hogar
0,20194,sb11201940125751,urbano,no,a,academico,411769000127,411769000127,702142,bogota,...,310.0,2019,3.5,2,2,2002-11-14,16.1,1.750000,2,4
1,20194,sb11201940049452,urbano,no,a,academico,111279000168,111279000168,73031,bogota,...,217.0,2019,3.5,3,2,2000-02-13,18.9,1.166667,0,1
2,20194,sb11201940292128,urbano,no,a,academico,111279000966,111279000966,25163,bogota,...,261.0,2019,5.5,2,3,2001-10-16,17.2,2.750000,2,3
3,20194,sb11201940062240,urbano,no,a,academico,111001020095,111001020095,113043,bogota,...,289.0,2019,7.5,6,2,2002-05-20,16.6,1.250000,2,3
4,20194,sb11201940135822,urbano,no,a,tecnico/academico,111001013129,111001013129,90787,bogota,...,267.0,2019,1.5,1,3,2003-04-29,15.7,1.500000,2,2

In [2]:
# ==========================================
# REVISAR VARIABLES
# ==========================================

print(df.columns.tolist())

['periodo', 'estu_consecutivo', 'cole_area_ubicacion', 'cole_bilingue', 'cole_calendario', 'cole_caracter', 'cole_cod_dane_establecimiento', 'cole_cod_dane_sede', 'cole_codigo_icfes', 'cole_depto_ubicacion', 'cole_mcpio_ubicacion', 'cole_genero', 'cole_jornada', 'cole_naturaleza', 'cole_nombre_establecimiento', 'cole_nombre_sede', 'cole_sede_principal', 'estu_depto_reside', 'estu_mcpio_reside', 'estu_depto_presentacion', 'estu_mcpio_presentacion', 'estu_estudiante', 'estu_fechanacimiento', 'estu_genero', 'estu_nacionalidad', 'estu_pais_reside', 'estu_privado_libertad', 'fami_cuartoshogar', 'fami_educacionmadre', 'fami_educacionpadre', 'fami_estratovivienda', 'fami_personashogar', 'fami_tieneautomovil', 'fami_tienecomputador', 'fami_tieneinternet', 'fami_tienelavadora', 'desemp_ingles', 'punt_ingles', 'punt_matematicas', 'punt_sociales_ciudadanas', 'punt_c_naturales', 'punt_lectura_critica', 'punt_global', 'anio', 'fami_personashogar_num', 'fami_cuartoshogar_num', 'fami_estratovivienda_num', 'estu_fechanacimiento_dt', 'edad', 'densidad_hogar', 'indice_tecnologico', 'indice_bienes_hogar']

In [3]:
# ==========================================
# DISTRIBUCIÓN VARIABLE OBJETIVO
# ==========================================

print(
    df["desemp_ingles"]
    .value_counts()
)

print(
    df["desemp_ingles"]
    .value_counts(normalize=True)
)

desemp_ingles
a1    98441
a-    82684
a2    60050
b1    41071
b+    19477
Name: count, dtype: int64
desemp_ingles
a1    0.326263
a-    0.274039
a2    0.199024
b1    0.136122
b+    0.064553
Name: proportion, dtype: float64

In [4]:
# ==========================================
# VARIABLES DEL ESTABLECIMIENTO EDUCATIVO
# ==========================================

variables_modelo = [

    "cole_area_ubicacion",
    "cole_bilingue",
    "cole_calendario",
    "cole_caracter",
    "cole_depto_ubicacion",
    "cole_genero",
    "cole_jornada",
    "cole_naturaleza",
    "cole_sede_principal"
]

target = "desemp_ingles"

# dataset final
df_model = df[
    variables_modelo + [target]
].copy()

print(df_model.shape)

df_model.head()

(301723, 10)

,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_depto_ubicacion,cole_genero,cole_jornada,cole_naturaleza,cole_sede_principal,desemp_ingles
0,urbano,no,a,academico,bogota,mixto,unica,no oficial,si,b1
1,urbano,no,a,academico,bogota,mixto,manana,oficial,si,a-
2,urbano,no,a,academico,bogota,mixto,manana,oficial,si,a1
3,urbano,no,a,academico,bogota,mixto,manana,oficial,si,a1
4,urbano,no,a,tecnico/academico,bogota,mixto,tarde,oficial,si,a2